In [68]:
import numpy as np
import pandas as pd
data = pd.read_csv('http://mlr.cs.umass.edu/ml/machine-learning-databases/adult/adult.data',
                   names = ["age","workclass","fnlwgt","education","education_num","marital-status","occupation",
                            "relationship","race","sex","capital-gain","capital-loss","hours-per-week",
                            "native-country","income-level"], sep=',\s', engine='python')

In [69]:
data[0::10]

,age,workclass,fnlwgt,education,education_num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income-level
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
20,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
30,23,Local-gov,190709,Assoc-acdm,12,Never-married,Protective-serv,Not-in-family,White,Male,0,0,52,United-States,<=50K
40,31,Private,507875,9th,5,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,43,United-States,<=50K
50,25,Private,32275,Some-college,10,Married-civ-spouse,Exec-managerial,Wife,Other,Female,0,0,40,United-States,<=50K
60,30,Private,59496,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,2407,0,40,United-States,<=50K
70,19,Private,101509,Some-college,10,Never-married,Prof-specialty,Own-child,White,Male,0,0,32,United-States,<=50K
80,18,Private,446839,HS-grad,9,Never-married,Sales,Not-in-family,White,Male,0,0,30,United-States,<=50K
90,57,Private,249977,Assoc-voc,11,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
100,76,Private,124191,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
110,24,Private,432376,Bachelors,13,Never-married,Sales,Other-relative,White,Male,0,0,40,United-States,<=50K
120,21,Private,199915,Some-college,10,Never-married,Other-service,Own-child,White,Female,0,0,40,United-States,<=50K
130,28,Private,69621,Assoc-acdm,12,Never-married,Sales,Not-in-family,White,Female,0,0,60,United-States,<=50K
140,61,Self-emp-inc,66614,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
150,47,Local-gov,186009,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,38,Mexico,<=50K
160,68,?,38317,1st-4th,2,Divorced,?,Not-in-family,White,Female,0,0,20,United-States,<=50K
170,27,Private,124953,HS-grad,9,Never-married,Other-service,Not-in-family,White,Male,0,1980,40,United-States,<=50K
180,44,Local-gov,181344,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,38,United-States,>50K
190,38,Private,155222,Some-college,10,Divorced,Machine-op-inspct,Not-in-family,Black,Female,0,0,28,United-States,<=50K
200,26,Private,397317,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,0,1876,40,United-States,<=50K
210,44,Local-gov,160943,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,Black,Male,0,0,40,United-States,<=50K
220,31,Private,197860,Some-college,10,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,0,0,40,United-States,<=50K
230,35,Private,538583,11th,7,Separated,Transport-moving,Not-in-family,Black,Male,3674,0,40,United-States,<=50K
240,40,Private,347890,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,>50K
250,41,Private,112763,Prof-school,15,Married-civ-spouse,Prof-specialty,Wife,White,Female,0,0,40,United-States,>50K
260,36,Private,150042,Bachelors,13,Divorced,Prof-specialty,Own-child,White,Female,0,0,40,United-States,<=50K
270,61,Private,69867,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
280,22,Private,34918,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,15,Germany,<=50K
290,36,Private,200352,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,45,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32270,60,Private,127084,HS-grad,9,Married-civ-spouse,Protective-serv,Husband,White,Male,0,2042,34,United-States,<=50K
32280,49,Private,255466,Some-college,10,Divorced,Adm-clerical,Not-in-family,White,Female,0,0,60,United-States,<=50K
32290,31,Private,47151,HS-grad,9,Never-married,Other-service,Not-in-family,White,Female,0,0,56,United-States,<=50K
32300,61,Private,232719,Masters,14,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K
32310,21,?,205939,Some-college,10,Never-married,?,Own-child,White,Male,0,0,40,United-States,<=50K
32320,37,Private,328466,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,72,Mexico,<=50K
32330,24,Private,118657,12th,8,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,<=50K
32340,75,Self-emp-not-inc,192813,Masters,14,Widowed,Sales,Not-in-family,White,Male,0,0,45,United-States,<=50K
32350,53,Private,291755,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
32360,58,State-gov,200316,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
32370,53,Self-emp-not-inc,137547,Prof-school,15,Never-married,Prof-specialty,Not-in-family,Asian-Pac-Islander,Male,27828,0,40,Philippines,>50K
32380,48,State-gov,224474,Some-college,10,Divorced,Exec-managerial,Not-in-family,White,Female,0,0,40,United-States,<=50K
32390,60,Private,56248,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,0,0,40,United-States,<=50K
32400,53,Local-gov,186303,Some-college,10,Married-civ-spouse,Protective-serv,Husband,White,Male,0,1887,40,United-States,>50K
32410,29,Private,183854,HS-grad,9,Never-married,Sales,Not-in-family,White,Female,0,0,25,United-States,<=50K
32420,23,Private,45834,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,50,United-States,<=50K
32430,61,Self-emp-not-inc,50483,7th-8th,4,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,56,United-States,<=50K
32440,30,Self-emp-not-inc,176185,Some-college,10,Married-spouse-absent,Craft-repair,Own-child,White,Male,0,0,60,United-States,>50K
32450,38,Private,257416,9th,5,Married-civ-spouse,Transport-moving,Husband,Black,Male,0,0,40,United-States,<=50K
32460,62,Private,128092,HS-grad,9,Widowed,Adm-clerical,Not-in-family,White,Female,0,0,32,United-States,<=50K
32470,50,Private,485710,Doctorate,16,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,50,United-States,<=50K
32480,41,Private,201495,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
32490,60,?,134152,9th,5,Divorced,?,Not-in-family,Black,Male,0,0,35,United-States,<=50K
32500,34,Private,60567,11th,7,Divorced,Transport-moving,Unmarried,White,Male,0,880,60,United-States,<=50K
32510,39,Private,107302,HS-grad,9,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,45,?,>50K
32520,27,Private,177398,HS-grad,9,Never-married,Other-service,Unmarried,White,Female,0,0,64,United-States,<=50K
32530,35,?,320084,Bachelors,13,Married-civ-spouse,?,Wife,White,Female,0,0,55,United-States,>50K
32540,45,State-gov,252208,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
32550,43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

## Replace all empty numeric fields with the average of its column in this new column.

In [70]:

data.fillna(data.mean)

,age,workclass,fnlwgt,education,education_num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income-level
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
12,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
13,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
14,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,>50K
15,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
16,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
17,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
18,38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
19,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
20,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
21,54,Private,302146,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
22,35,Federal-gov,76845,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K
23,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
24,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
25,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
26,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
27,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
28,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
29,49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32531,30,?,33811,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,<=50K
32532,34,Private,204461,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
32533,54,Private,337992,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,50,Japan,>50K
32534,37,Private,179137,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,39,United-States,<=50K
32535,22,Private,325033,12th,8,Never-married,Protective-serv,Own-child,Black,Male,0,0,35,United-States,<=50K
32536,34,Private,160216,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,>50K
32537,30,Private,345898,HS-grad,9,Never-married,Craft-repair,Not-in-family,Black,Male,0,0,46,United-States,<=50K
32538,38,Private,139180,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,15020,0,45,United-States,>50K
32539,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K
32540,45,State-gov,252208,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
32541,41,?,202822,HS-grad,9,Separated,?,Not-in-family,Black,Female,0,0,32,United-States,<=50K
32542,72,?,129912,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,25,United-States,<=50K
32543,45,Local-gov,119199,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,0,0,48,United-States,<=50K
32544,31,Private,199655,Masters,14,Divorced,Other-service,Not-in-family,Other,Female,0,0,30,United-States,<=50K
32545,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K
32546,37,Private,198216,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States,<=50K
32547,43,Private,260761,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,Mexico,<=50K
32548,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
32549,43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K
32550,43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,<=50K
32551,32,Private,34066,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K
32552,43,Private,84661,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,0,0,45,United-States,<=50K
32553,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
32554,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
32555,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

##  for all values that are "?", find the value that is most common in the column it is found and replace the "?" with it.

In [71]:
for column in data:
    data[column].replace("?", data[column].mode().iloc[0], inplace=True)
data[0::10]

,age,workclass,fnlwgt,education,education_num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income-level
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
20,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
30,23,Local-gov,190709,Assoc-acdm,12,Never-married,Protective-serv,Not-in-family,White,Male,0,0,52,United-States,<=50K
40,31,Private,507875,9th,5,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,43,United-States,<=50K
50,25,Private,32275,Some-college,10,Married-civ-spouse,Exec-managerial,Wife,Other,Female,0,0,40,United-States,<=50K
60,30,Private,59496,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,2407,0,40,United-States,<=50K
70,19,Private,101509,Some-college,10,Never-married,Prof-specialty,Own-child,White,Male,0,0,32,United-States,<=50K
80,18,Private,446839,HS-grad,9,Never-married,Sales,Not-in-family,White,Male,0,0,30,United-States,<=50K
90,57,Private,249977,Assoc-voc,11,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
100,76,Private,124191,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
110,24,Private,432376,Bachelors,13,Never-married,Sales,Other-relative,White,Male,0,0,40,United-States,<=50K
120,21,Private,199915,Some-college,10,Never-married,Other-service,Own-child,White,Female,0,0,40,United-States,<=50K
130,28,Private,69621,Assoc-acdm,12,Never-married,Sales,Not-in-family,White,Female,0,0,60,United-States,<=50K
140,61,Self-emp-inc,66614,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
150,47,Local-gov,186009,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,38,Mexico,<=50K
160,68,Private,38317,1st-4th,2,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,20,United-States,<=50K
170,27,Private,124953,HS-grad,9,Never-married,Other-service,Not-in-family,White,Male,0,1980,40,United-States,<=50K
180,44,Local-gov,181344,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,38,United-States,>50K
190,38,Private,155222,Some-college,10,Divorced,Machine-op-inspct,Not-in-family,Black,Female,0,0,28,United-States,<=50K
200,26,Private,397317,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,0,1876,40,United-States,<=50K
210,44,Local-gov,160943,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,Black,Male,0,0,40,United-States,<=50K
220,31,Private,197860,Some-college,10,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,0,0,40,United-States,<=50K
230,35,Private,538583,11th,7,Separated,Transport-moving,Not-in-family,Black,Male,3674,0,40,United-States,<=50K
240,40,Private,347890,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,>50K
250,41,Private,112763,Prof-school,15,Married-civ-spouse,Prof-specialty,Wife,White,Female,0,0,40,United-States,>50K
260,36,Private,150042,Bachelors,13,Divorced,Prof-specialty,Own-child,White,Female,0,0,40,United-States,<=50K
270,61,Private,69867,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
280,22,Private,34918,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,15,Germany,<=50K
290,36,Private,200352,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,45,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32270,60,Private,127084,HS-grad,9,Married-civ-spouse,Protective-serv,Husband,White,Male,0,2042,34,United-States,<=50K
32280,49,Private,255466,Some-college,10,Divorced,Adm-clerical,Not-in-family,White,Female,0,0,60,United-States,<=50K
32290,31,Private,47151,HS-grad,9,Never-married,Other-service,Not-in-family,White,Female,0,0,56,United-States,<=50K
32300,61,Private,232719,Masters,14,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K
32310,21,Private,205939,Some-college,10,Never-married,Prof-specialty,Own-child,White,Male,0,0,40,United-States,<=50K
32320,37,Private,328466,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,72,Mexico,<=50K
32330,24,Private,118657,12th,8,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,<=50K
32340,75,Self-emp-not-inc,192813,Masters,14,Widowed,Sales,Not-in-family,White,Male,0,0,45,United-States,<=50K
32350,53,Private,291755,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
32360,58,State-gov,200316,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
32370,53,Self-emp-not-inc,137547,Prof-school,15,Never-married,Prof-specialty,Not-in-family,Asian-Pac-Islander,Male,27828,0,40,Philippines,>50K
32380,48,State-gov,224474,Some-college,10,Divorced,Exec-managerial,Not-in-family,White,Female,0,0,40,United-States,<=50K
32390,60,Private,56248,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,0,0,40,United-States,<=50K
32400,53,Local-gov,186303,Some-college,10,Married-civ-spouse,Protective-serv,Husband,White,Male,0,1887,40,United-States,>50K
32410,29,Private,183854,HS-grad,9,Never-married,Sales,Not-in-family,White,Female,0,0,25,United-States,<=50K
32420,23,Private,45834,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,50,United-States,<=50K
32430,61,Self-emp-not-inc,50483,7th-8th,4,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,56,United-States,<=50K
32440,30,Self-emp-not-inc,176185,Some-college,10,Married-spouse-absent,Craft-repair,Own-child,White,Male,0,0,60,United-States,>50K
32450,38,Private,257416,9th,5,Married-civ-spouse,Transport-moving,Husband,Black,Male,0,0,40,United-States,<=50K
32460,62,Private,128092,HS-grad,9,Widowed,Adm-clerical,Not-in-family,White,Female,0,0,32,United-States,<=50K
32470,50,Private,485710,Doctorate,16,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,50,United-States,<=50K
32480,41,Private,201495,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
32490,60,Private,134152,9th,5,Divorced,Prof-specialty,Not-in-family,Black,Male,0,0,35,United-States,<=50K
32500,34,Private,60567,11th,7,Divorced,Transport-moving,Unmarried,White,Male,0,880,60,United-States,<=50K
32510,39,Private,107302,HS-grad,9,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,45,United-States,>50K
32520,27,Private,177398,HS-grad,9,Never-married,Other-service,Unmarried,White,Female,0,0,64,United-States,<=50K
32530,35,Private,320084,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,White,Female,0,0,55,United-States,>50K
32540,45,State-gov,252208,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
32550,43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

# Convert non-numeric columns to columns with an integer representations

In [104]:
def encode_target(df_mod, target_column):
    targets = df_mod[target_column].unique()
    map_to_int = {name: n for n, name in enumerate(targets)}
    for name in map_to_int:
        df_mod[target_column].replace(name, map_to_int[name], inplace=True)

df = data.copy()
encode_target(df, "workclass")
encode_target(df, "education")
encode_target(df, "marital-status")
encode_target(df, "occupation")
encode_target(df, "relationship")
encode_target(df, "race")
encode_target(df, "sex")
encode_target(df, "native-country")
encode_target(df, "income-level")

df[0::10]

,age,workclass,fnlwgt,education,education_num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income-level
0,39,0,77516,0,13,0,0,0,0,0,2174,0,40,0,0
10,37,2,280464,5,10,1,1,1,1,0,0,0,80,0,1
20,40,2,193524,9,16,1,3,1,0,0,0,0,60,0,1
30,23,4,190709,6,12,0,11,0,0,0,0,0,52,0,0
40,31,2,507875,4,5,1,9,1,0,0,0,0,43,0,0
50,25,2,32275,5,10,1,1,2,4,1,0,0,40,0,0
60,30,2,59496,0,13,1,5,1,0,0,2407,0,40,0,0
70,19,2,101509,5,10,0,3,3,0,0,0,0,32,0,0
80,18,2,446839,1,9,0,5,0,0,0,0,0,30,0,0
90,57,2,249977,7,11,1,3,1,0,0,0,0,40,0,0
100,76,2,124191,3,14,1,1,1,0,0,0,0,40,0,1
110,24,2,432376,0,13,0,5,5,0,0,0,0,40,0,0
120,21,2,199915,5,10,0,4,3,0,1,0,0,40,0,0
130,28,2,69621,6,12,0,5,0,0,1,0,0,60,0,0
140,61,5,66614,1,9,1,6,1,0,0,0,0,40,0,0
150,47,4,186009,5,10,2,0,4,0,1,0,0,38,4,0
160,68,2,38317,13,2,2,3,0,0,1,0,0,20,0,0
170,27,2,124953,1,9,0,4,0,0,0,0,1980,40,0,0
180,44,4,181344,5,10,1,1,1,1,0,0,0,38,0,1
190,38,2,155222,5,10,2,9,0,1,1,0,0,28,0,0
200,26,2,397317,3,14,0,3,0,0,1,0,1876,40,0,0
210,44,4,160943,1,9,1,7,1,1,0,0,0,40,0,0
220,31,2,197860,5,10,1,2,1,0,0,0,0,40,0,0
230,35,2,538583,2,7,4,7,0,1,0,3674,0,40,0,0
240,40,2,347890,0,13,1,3,1,0,0,0,0,40,0,1
250,41,2,112763,10,15,1,3,2,0,1,0,0,40,0,1
260,36,2,150042,0,13,2,3,3,0,1,0,0,40,0,0
270,61,2,69867,1,9,1,1,1,0,0,0,0,40,0,1
280,22,2,34918,0,13,0,3,0,0,1,0,0,15,10,0
290,36,2,200352,0,13,1,3,1,0,0,0,0,45,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32270,60,2,127084,1,9,1,11,1,0,0,0,2042,34,0,0
32280,49,2,255466,5,10,2,0,0,0,1,0,0,60,0,0
32290,31,2,47151,1,9,0,4,0,0,1,0,0,56,0,0
32300,61,2,232719,3,14,1,3,1,0,0,0,0,50,0,0
32310,21,2,205939,5,10,0,3,3,0,0,0,0,40,0,0
32320,37,2,328466,1,9,1,6,1,0,0,0,0,72,4,0
32330,24,2,118657,15,8,1,9,1,0,0,0,0,40,0,0
32340,75,1,192813,3,14,6,5,0,0,0,0,0,45,0,0
32350,53,2,291755,7,11,1,6,1,0,0,0,0,40,0,0
32360,58,0,200316,1,9,1,6,1,0,0,0,0,40,0,0
32370,53,1,137547,10,15,0,3,0,2,0,27828,0,40,12,1
32380,48,0,224474,5,10,2,1,0,0,1,0,0,40,0,0
32390,60,2,56248,5,10,1,5,1,0,0,0,0,40,0,0
32400,53,4,186303,5,10,1,11,1,0,0,0,1887,40,0,1
32410,29,2,183854,1,9,0,5,0,0,1,0,0,25,0,0
32420,23,2,45834,0,13,0,1,0,0,1,0,0,50,0,0
32430,61,1,50483,8,4,1,8,1,0,0,0,0,56,0,0
32440,30,1,176185,5,10,3,6,3,0,0,0,0,60,0,1
32450,38,2,257416,4,5,1,7,1,1,0,0,0,40,0,0
32460,62,2,128092,1,9,6,0,0,0,1,0,0,32,0,0
32470,50,2,485710,9,16,2,3,0,0,1,0,0,50,0,0
32480,41,2,201495,3,14,1,1,1,0,0,0,0,40,0,1
32490,60,2,134152,4,5,2,3,0,1,0,0,0,35,0,0
32500,34,2,60567,2,7,2,7,4,0,0,0,880,60,0,0
32510,39,2,107302,1,9,1,3,1,0,0,0,0,45,0,1
32520,27,2,177398,1,9,0,4,4,0,1,0,0,64,0,0
32530,35,2,320084,0,13,1,3,2,0,1,0,0,55,0,1
32540,45,0,252208,1,9,4,0,3,0,1,0,0,40,0,0
32550,43,1,27242,5,10,1,6,1,0,0,0,0,50,0,0
32560,52,5,287927,1,9,1,1,2,0,1,15024,0,40,0,1

## Convert the data to a numpy array if it isn't one already.

In [113]:
a = np.array(df)
a[0]

array([   39,     0, 77516,     0,    13,     0,     0,     0,     0,
           0,  2174,     0,    40,     0,     0], dtype=int64)

## Divide the data into a training and test set.

In [120]:
Y = a[:,-1]
X = a[:,0:-1]
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.3, random_state=2)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(22792, 14)
(9769, 14)
(22792,)
(9769,)

## Run both a random forest and gaussian naive bayes on the training set
## Compute the accuracy of predictions on the test set.

In [121]:
from sklearn import tree
clf = tree.DecisionTreeClassifier(criterion="entropy")
clf.fit(X_train, Y_train)
acc_train = clf.score(X_train, Y_train)
acc_test = clf.score(X_test, Y_test)

print("Accuracy on training data:", acc_train)
print("Accuracy on test data:", acc_test)

Accuracy on training data: 1.0
Accuracy on test data: 0.808987613881

In [123]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

gnb.fit(X_train, Y_train)
acc_train = gnb.score(X_train, Y_train)
acc_test = gnb.score(X_test, Y_test)

print("Accuracy on training data:", acc_train)
print("Accuracy on test data:", acc_test)

Accuracy on training data: 0.797560547561
Accuracy on test data: 0.791073804893

## Use another additional classifier

In [124]:
from sklearn import tree
clf = tree.DecisionTreeClassifier(criterion="gini")
clf.fit(X_train, Y_train)
acc_train = clf.score(X_train, Y_train)
acc_test = clf.score(X_test, Y_test)

print("Accuracy on training data:", acc_train)
print("Accuracy on test data:", acc_test)

Accuracy on training data: 1.0
Accuracy on test data: 0.804381205855